apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-withurl-sept25 
  janus-idp.io/tekton: test-withurl-sept25
  backstage.io/kubernetes-id: test-withurl-sept25
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-withurl-sept25
resources: 
- application-dev.yaml